POST http://192.168.0.30/admin/192.168.0.30/admin/registro
Content-Type: application/json

{
    "nombre": "Jose3",
    "apellido": "Lopez3",
    "usuario": "Josema",
    "correo": "jose",
    "password": "123456",
    "tipo": "admin"
    }